apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kserve-models-web-app
  namespace: kserve
spec:
  gateways:
  - $(ingressGateway)
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /models/
    rewrite:
      uri: /
    route:
    - destination:
        host: kserve-models-web-app.kserve.svc.cluster.local
        port:
          number: 80
