apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kserve
    app.kubernetes.io/instance: kserve-controller-manager
    app.kubernetes.io/managed-by: kserve-controller-manager
    app.kubernetes.io/name: kserve
  name: kserve-controller-manager
  namespace: {{ .Release.Namespace }}
