apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kserve
    app.kubernetes.io/name: kserve
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
  name: kserve-controller-manager-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: kserve-controller-manager
    controller-tools.k8s.io: "1.0"
