apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: llminferenceservice.serving.kserve.io
webhooks:
  - clientConfig:
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1alpha2-llminferenceservice
    failurePolicy: Fail
    name: llminferenceservice.kserve-webhook-server.v1alpha2.validator
    sideEffects: None
    admissionReviewVersions: [ "v1", "v1beta1" ]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - llminferenceservices
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: llminferenceserviceconfig.serving.kserve.io
webhooks:
  - clientConfig:
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1alpha2-llminferenceserviceconfig
    failurePolicy: Fail
    name: llminferenceserviceconfig.kserve-webhook-server.v1alpha2.validator
    sideEffects: None
    admissionReviewVersions: [ "v1", "v1beta1" ]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - llminferenceserviceconfigs
