apiVersion: v1
kind: Service
metadata:
  name: llmisvc-webhook-svc
  namespace: kserve
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    control-plane: llmisvc-controller-manager
