[tool.poetry]
name = "lgbserver"
version = "0.11.0"
description = "Model Server implementation for LightGBM. Not intended for use outside KServe Frameworks Images."
authors = ["Lin Yiming <linyiming@ainnovation.com>"]
license = "https://github.com/kserve/kserve/blob/master/LICENSE"
readme = "README.md"
packages = [
    { include = "lgbserver" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
kserve = { path = "../kserve", extras = ["storage"], develop = true }
lightgbm = "~3.3.2"
pandas = "^1.3.5"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.3"
pytest-cov = "^4.0.0"
mypy = "^0.991"

[tool.poetry-version-plugin]
source = "file"
file_path = "../VERSION"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
