[project]
authors = [
    {name = "singhan", email = "singhan@us.ibm.com"},
]
license = {text = "https://github.com/kserve/kserve/blob/master/LICENSE"}
requires-python = "<3.13,>=3.9"
dependencies = [
    "kserve[storage] @ file:///${PROJECT_ROOT}/../kserve",
    "scikit-learn~=1.5.1",
    "joblib<2.0.0,>=1.4.0",
    "pandas<3.0.0,>=2.2.0",
]
name = "sklearnserver"
version = "0.15.2"
description = "Model Server implementation for scikit-learn. Not intended for use outside KServe Frameworks Images."
authors = ["singhan <singhan@us.ibm.com>"]
license = "Apache-2.0"
readme = "README.md"

[dependency-groups]
test = [
    "pytest<8.0.0,>=7.2.0",
    "pytest-cov<5.0.0,>=4.0.0",
    "mypy<1.0,>=0.991",
    "pytest-asyncio<1.0.0,>=0.23.4",
]
dev = [
    "black[colorama]~=24.3.0",
]
