apiVersion: v1
name: kserve-crd-minimal
version: v0.14.1
description: Helm chart for deploying minimal kserve crds without validation
keywords:
  - kserve
  - modelmesh
sources:
  - http://github.com/kserve/kserve
