apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

components:
- ../../components/kserve
- ../../components/llmisvc
- ../../components/localmodel

patches:
- path: configmap/inferenceservice_patch.yaml
- path: manager_image_patch.yaml
- path: localmodelnode_image_patch.yaml
- path: localmodel_image_patch.yaml
- path: llmisvc_image_patch.yaml
