apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serving.kserve.io_localmodelcaches.yaml
  - serving.kserve.io_localmodelnodegroups.yaml
  - serving.kserve.io_localmodelnodes.yaml
