apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: kubeflow

# Labels to add to all resources and selectors.
commonLabels:
  app: kfserving
  app.kubernetes.io/name: kfserving

bases:
- ../../default
- cluster-role.yaml
- web-app-authorization-policy.yaml

patchesStrategicMerge:
- patches/statefulset.yaml
- patches/namespace.yaml
- patches/web-app-vsvc.yaml
- patches/web-app-sidecar.yaml

generatorOptions:
  disableNameSuffixHash: true

# To make namespace for standalone installation kustomizable,
# variabalize ingress gateway, webhook service name and
# kfserving namespace in webhook configurations
configMapGenerator:
  - name: kfserving-config
    behavior: replace
    envs:
    - params.env
  - name: models-web-app-config
    behavior: replace
    literals:
    - USERID_HEADER=kubeflow-userid

configurations:
- params.yaml
