apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: kubeflow

# Labels to add to all resources and selectors.
commonLabels:
  app: kserve
  app.kubernetes.io/name: kserve

bases:
- ../../default
- cluster-role.yaml
- web-app-authorization-policy.yaml

patchesStrategicMerge:
- patches/statefulset.yaml
- patches/namespace.yaml
- patches/web-app-sidecar.yaml

patchesJson6902:
- target:
    group: networking.istio.io
    version: v1beta1
    kind: VirtualService
    name: kserve-models-web-app
    namespace: kserve
  path: patches/web-app-vsvc.yaml

generatorOptions:
  disableNameSuffixHash: true

# To make namespace for standalone installation kustomizable,
# variabalize ingress gateway, webhook service name and
# kserve namespace in webhook configurations
configMapGenerator:
  - name: kserve-config
    behavior: replace
    envs:
    - params.env
  - name: kserve-models-web-app-config
    behavior: replace
    literals:
    - USERID_HEADER=kubeflow-userid

configurations:
- params.yaml
