apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: kfservices.serving.kubeflow.org
spec:
  group: serving.kubeflow.org
  names:
    kind: KFService
    plural: kfservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            canary:
              description: Optional Canary definition
              properties:
                custom:
                  description: The following fields follow a "1-of" semantic. Users
                    must specify exactly one spec.
                  properties:
                    container:
                      type: object
                  required:
                  - container
                  type: object
                scikitLearn:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest ScikitLearn Version.
                      type: string
                  required:
                  - modelUri
                  type: object
                tensorflow:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest TF Version.
                      type: string
                  required:
                  - modelUri
                  type: object
                trafficPercent:
                  format: int32
                  type: integer
                xgBoost:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest XGBoost Version.
                      type: string
                  required:
                  - modelUri
                  type: object
              required:
              - trafficPercent
              type: object
            default:
              properties:
                custom:
                  description: The following fields follow a "1-of" semantic. Users
                    must specify exactly one spec.
                  properties:
                    container:
                      type: object
                  required:
                  - container
                  type: object
                scikitLearn:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest ScikitLearn Version.
                      type: string
                  required:
                  - modelUri
                  type: object
                tensorflow:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest TF Version.
                      type: string
                  required:
                  - modelUri
                  type: object
                xgBoost:
                  properties:
                    modelUri:
                      type: string
                    resources:
                      description: Defaults to requests and limits of 1CPU, 2Gb MEM.
                      type: object
                    runtimeVersion:
                      description: Defaults to latest XGBoost Version.
                      type: string
                  required:
                  - modelUri
                  type: object
              type: object
            maxReplicas:
              format: int32
              type: integer
            minReplicas:
              format: int32
              type: integer
          required:
          - minReplicas
          - maxReplicas
          - default
          type: object
        status:
          properties:
            canary:
              properties:
                name:
                  type: string
                replicas:
                  format: int64
                  type: integer
                traffic:
                  format: int64
                  type: integer
              type: object
            conditions:
              properties:
                lastProbeTime:
                  description: Last time the condition was probed.
                  format: date-time
                  type: string
                lastTransitionTime:
                  description: Last time the condition transitioned from one status
                    to another.
                  format: date-time
                  type: string
                message:
                  description: Human-readable message indicating details about last
                    transition.
                  type: string
                reason:
                  description: Unique, one-word, CamelCase reason for the condition's
                    last transition.
                  type: string
                status:
                  type: string
                type:
                  type: string
              required:
              - type
              - status
              type: object
            default:
              properties:
                name:
                  type: string
                replicas:
                  format: int64
                  type: integer
                traffic:
                  format: int64
                  type: integer
              type: object
            uri:
              properties:
                external:
                  type: string
                internal:
                  type: string
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
