apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-paddleserver
spec:
  supportedModelTypes:
    - name: paddle
      version: "0"
  containers:
    - name: kserve-container
      image: kserve-paddleserver:replace
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
        - --http_port=8080
