# Patch to add conversion webhook configuration to LLMInferenceServiceConfig CRD
# This enables automatic v1alpha1 <-> v1alpha2 API version conversion
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: llminferenceserviceconfigs.serving.kserve.io
  annotations:
    cert-manager.io/inject-ca-from: kserve/llmisvc-serving-cert
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: llmisvc-webhook-server-service
          namespace: kserve
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1
        - v1beta1
