[tool.poetry]
name = "kserve"
version = "0.12.1"
description = "KServe Python SDK"
authors = [
    "The KServe Authors <dsun20@bloomberg.net>",
    "The KServe Authors <ellisbigelow@google.com>",
    "The KServe Authors <hejinchi@cn.ibm.com>",
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/kserve/kserve/tree/master/python/kserve"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "kserve" },
]
exclude = ["kserve/storage/test"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
uvicorn = { version = "^0.21.1", extras = ["standard"] }
fastapi = "^0.109.1"
cloudevents = "^1.6.2"
six = "^1.16.0"
kubernetes = ">=23.3.0"
python-dateutil = "^2.8.0"
numpy = "^1.23.5"
psutil = "^5.9.0"
ray = { version = "~2.10.0", extras = ["serve"] }
grpcio = "^1.49.1"
protobuf = "^3.19.0"
prometheus-client = "^0.20.0"
orjson = "^3.9.15"
httpx = "^0.26.0"
timing-asgi = "^0.3.0"
tabulate = "^0.9.0"
pandas = ">=1.3.5"
pydantic = ">1.0,<3"

# Storage dependencies. They can be opted into by apps.
requests = { version = "^2.20.0", optional = true }
google-cloud-storage = { version = "^2.3.0", optional = true }
azure-storage-blob = { version = "^12.10.0", optional = true }
azure-storage-file-share = { version = "^12.7.0", optional = true }
azure-identity = { version = "^1.8.0", optional = true }
boto3 = { version = "^1.21.0", optional = true }

# Logging dependencies. They can be opted into by apps.
asgi-logger = { version = "^0.1.0", optional = true, python = ">3.8.0,<3.11" }

[tool.poetry.extras]
storage = [
    "requests",
    "google-cloud-storage",
    "azure-storage-blob",
    "azure-storage-file-share",
    "azure-identity",
    "boto3",
]
logging = [
    "asgi-logger"
]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-xdist = "^3.0.2"
pytest-asyncio = "^0.20.2"
mypy = "^0.991"
portforward = "^0.4.3"
avro = "^1.11.0"
tomlkit = "^0.11.6"
jinja2 = "^3.1.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = { version = "~24.3.0", extras = ["colorama"] }

[tool.poetry-version-plugin]
source = "file"
file_path = "../VERSION"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
