apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  labels:
  {{- include "kserve-resources.labels" . | nindent 4 }}
data:
  _example: {{ .Values.inferenceserviceConfig.Example | toYaml | indent 1 }}
  agent: |-
{{ .Values.inferenceserviceConfig.agent | indent 4 }}
  autoscaler: |-
{{ .Values.inferenceserviceConfig.autoscaler | indent 4 }}
  batcher: |-
{{ .Values.inferenceserviceConfig.batcher | indent 4 }}
  credentials: |-
{{ .Values.inferenceserviceConfig.credentials | indent 4 }}
  deploy: |-
{{ .Values.inferenceserviceConfig.deploy | indent 4 }}
  explainers: |-
{{ .Values.inferenceserviceConfig.explainers | indent 4 }}
  inferenceService: |-
{{ .Values.inferenceserviceConfig.inferenceService | indent 4 }}
  ingress: |-
{{ .Values.inferenceserviceConfig.ingress | indent 4 }}
  localModel: |-
{{ .Values.inferenceserviceConfig.localModel | indent 4 }}
  logger: |-
{{ .Values.inferenceserviceConfig.logger | indent 4 }}
  metricsAggregator: |-
{{ .Values.inferenceserviceConfig.metricsAggregator | indent 4 }}
  opentelemetryCollector: |-
{{ .Values.inferenceserviceConfig.opentelemetryCollector | indent 4 }}
  router: |-
{{ .Values.inferenceserviceConfig.router | indent 4 }}
  security: |-
{{ .Values.inferenceserviceConfig.security | indent 4 }}
  storageInitializer: |-
{{ .Values.inferenceserviceConfig.storageInitializer | indent 4 }}
