apiVersion: v1
kind: Service
metadata:
  name: {{ include "kserve-resources.fullname" . }}-llmisvc-mgr-svc
  labels:
    app.kubernetes.io/component: controller
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
  {{- include "kserve-resources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmisvcMgrSvc.type }}
  selector:
    control-plane: llmisvc-controller-manager
    controller-tools.k8s.io: "1.0"
    {{- include "kserve-resources.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.llmisvcMgrSvc.ports | toYaml | nindent 2 }}
