---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferenceservice.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /mutate-serving-kserve-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.defaulter
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /mutate-pods
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.pod-mutator
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions: ["v1beta1"]
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: serving.kserve.io/inferenceservice
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferenceservice.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: trainedmodel.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1alpha1-trainedmodel
    failurePolicy: Fail
    name: trainedmodel.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferencegraph.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1alpha1-inferencegraph
    failurePolicy: Fail
    name: inferencegraph.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferencegraphs
---
#apiVersion: admissionregistration.k8s.io/v1
#kind: ValidatingWebhookConfiguration
#metadata:
#  creationTimestamp: null
#  name: clusterservingruntime.serving.kserve.io
#webhooks:
#  - clientConfig:
#      caBundle: Cg==
#      service:
#        name: $(webhookServiceName)
#        namespace: $(kserveNamespace)
#        path: /validate-serving-kserve-io-v1alpha1-clusterservingruntime
#    failurePolicy: Fail
#    name: clusterservingruntime.kserve-webhook-server.validator
#    sideEffects: None
#    admissionReviewVersions: ["v1beta1"]
#    rules:
#      - apiGroups:
#          - serving.kserve.io
#        apiVersions:
#          - v1alpha1
#        operations:
#          - CREATE
#          - UPDATE
#        resources:
#          - clusterservingruntimes
#---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: servingruntime.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: $(webhookServiceName)
        namespace: $(kserveNamespace)
        path: /validate-serving-kserve-io-v1alpha1-servingruntime
    failurePolicy: Fail
    name: servingruntime.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servingruntimes
