{{- if .Values.kserve.modelmesh.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
  name: modelmesh-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelmesh-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: modelmesh-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
  name: modelmesh-controller-restricted-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelmesh-controller-restricted-scc
subjects:
- kind: ServiceAccount
  name: modelmesh-controller
{{- end }}
