apiVersion: v1
name: llmisvc-crd
version: v0.16.0-rc1
description: Helm chart for deploying LLMInferenceService crds 
keywords:
  - kserve
  - llm
  - llm-d
  - inference
  - generative-ai
  - machine-learning
  - model-serving
home: https://kserve.github.io/website/
sources:
  - https://github.com/kserve/kserve
maintainers:
  - name: KServe Team
    url: https://github.com/kserve/kserve
icon: https://raw.githubusercontent.com/kserve/website/main/docs/images/logo.png
annotations:
  category: AI/Machine Learning
