{{- if .Values.runtimes.enabled }}
{{- if .Values.runtimes.tensorflow.enabled }}
apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-tensorflow-serving
  labels:
    {{- include "kserve-runtime-configs.labels" . | nindent 4 }}
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
  containers:
  - args:
    - --model_name={{ "{{" }}.Name{{ "}}" }}
    - --port=9000
    - --rest_api_port=8080
    - --model_base_path=/mnt/models
    - --rest_api_timeout_in_ms=60000
    command:
    - /usr/bin/tensorflow_model_server
    image: {{ .Values.runtimes.tensorflow.image.repository }}:{{ .Values.runtimes.tensorflow.image.tag | default .Values.kserve.version }}
    name: kserve-container
    resources: {{- toYaml .Values.runtimes.tensorflow.resources | nindent 6 }}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
  protocolVersions:
  - v1
  - grpc-v1
  supportedModelFormats:
  - autoSelect: true
    name: tensorflow
    priority: 2
    version: "1"
  - autoSelect: true
    name: tensorflow
    priority: 2
    version: "2"
{{- end }}
{{- end }}
