- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/canary/properties/explainer/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/canary/properties/predictor/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/canary/properties/transformer/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/default/properties/explainer/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/default/properties/predictor/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/default/properties/transformer/properties/custom/properties/container/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/triton/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/pytorch/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/onnx/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/sklearn/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/xgboost/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/tensorflow/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/pmml/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/lightgbm/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/predictor/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/transformer/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/explainer/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/explainer/properties/aix/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/explainer/properties/art/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/explainer/properties/alibi/properties/ports/items/required/1
  value: protocol
