- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/triton/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/pytorch/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/onnx/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/huggingface/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/sklearn/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/xgboost/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/tensorflow/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/pmml/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/lightgbm/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/paddle/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/predictor/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/transformer/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/explainer/properties/containers/items/properties/ports/items/required/1
  value: protocol

- op: add
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/explainer/properties/art/properties/ports/items/required/1
  value: protocol
