apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llmisvc-leader-election-role
  labels:
  {{- include "kserve-llmisvc-resources.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llmisvc-leader-election-rolebinding
  labels:
  {{- include "kserve-llmisvc-resources.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llmisvc-leader-election-role
subjects:
- kind: ServiceAccount
  name: '{{ include "kserve-llmisvc-resources.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
