apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kserve-llmisvc-resources.fullname" . }}-llmisvc-serving-cert
  labels:
  {{- include "kserve-llmisvc-resources.labels" . | nindent 4 }}
spec:
  commonName: llmisvc-webhook-server-service.kserve.svc
  dnsNames:
  - '{{ include "kserve-llmisvc-resources.fullname" . }}-llmisvc-webhook-server-service.{{ .Release.Namespace
    }}.svc'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: llmisvc-webhook-server-cert
