apiVersion: v1
kind: Service
metadata:
  name: llmisvc-webhook-server-service
  labels:
  {{- include "kserve-llmisvc-resources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmisvcWebhookServerService.type }}
  selector:
    control-plane: llmisvc-controller-manager
    {{- include "kserve-llmisvc-resources.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.llmisvcWebhookServerService.ports | toYaml | nindent 2 }}
