apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-isvc-resources.fullname" . }}-llmisvc-webhook-svc
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmisvcWebhookSvc.type }}
  selector:
    control-plane: llmisvc-controller-manager
    {{- include "llm-isvc-resources.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.llmisvcWebhookSvc.ports | toYaml | nindent 2 }}
