apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kserve-llmisvc-resources.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "kserve-llmisvc-resources.labels" . | nindent 4 }}
spec:
  selfSigned: {}
