{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-isvc-resources.serviceAccountName" . }}
  labels:
  {{- include "llm-isvc-resources.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ "{{" }} - end {{ "}}" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ "{{" }} - end {{ "}}" }}
