---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: localmodelcachedeployments.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: LocalModelCacheDeployment
    listKind: LocalModelCacheDeploymentList
    plural: localmodelcachedeployments
    singular: localmodelcachedeployment
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.sourceModelUri
      name: SourceURI
      type: string
    - jsonPath: .status.currentRevision
      name: CurrentRevision
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LocalModelCacheDeployment is the Schema for the localmodels API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: LocalModelCacheDeploymentSpec defines the desired state of
              LocalModelCacheDeployment
            properties:
              modelSize:
                anyOf:
                - type: integer
                - type: string
                description: Size of the model for storage allocation
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              nodeGroups:
                description: Node groups to cache the model on
                items:
                  type: string
                minItems: 1
                type: array
              sourceModelUri:
                description: Source URI of the model (e.g., s3://bucket/model)
                type: string
            required:
            - modelSize
            - nodeGroups
            - sourceModelUri
            type: object
          status:
            description: LocalModelCacheDeploymentStatus defines the observed state
              of LocalModelCacheDeployment
            properties:
              currentRevision:
                description: Current active revision name
                type: string
              observedGeneration:
                description: ObservedGeneration is the last observed generation
                format: int64
                type: integer
              revisions:
                description: List of all revisions
                items:
                  description: LocalModelCacheDeploymentRevision represents a revision
                    of the LocalModelCacheDeployment
                  properties:
                    name:
                      description: Name of the LocalModelCache for this revision
                      type: string
                    revision:
                      description: Revision number
                      format: int32
                      type: integer
                  required:
                  - name
                  - revision
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
