kserve:
  agent:
    image: kserve/agent:v0.7.0
  storage:
    image: kserve/storage-initializer:v0.7.0
    s3:
      accessKeyIdName: AWS_ACCESS_KEY_ID
      secretAccessKeyName: AWS_SECRET_ACCESS_KEY
  controller:
    deploymentMode: "RawDeployment"
    gateway:
      domain: example.com
      localGateway:
        gateway: knative-serving/knative-local-gateway
        gatewayService: knative-local-gateway.istio-system.svc.cluster.local
      ingressGateway:
        gateway: knative-serving/knative-ingress-gateway
        gatewayService: istio-ingressgateway.istio-system.svc.cluster.local
    image: kserve/kserve-controller:v0.7.0
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 300Mi
  servingruntime:
    tfserving:
      image: tensorflow/serving
      defaultVersion: 1.14.0
      defaultGpuVersion: 1.14.0-gpu
    onnx:
      image: mcr.microsoft.com/onnxruntime/server
      defaultVersion: v1.0.0
    sklearn:
      v1:
        image: kserve/sklearnserver
        defaultVersion: v0.7.0
      v2:
        image: docker.io/seldonio/mlserver
        defaultVersion: 0.2.1
    xgboost:
      v1:
        image: kserve/xgbserver
        defaultVersion: v0.7.0
      v2:
        image: docker.io/seldonio/mlserver
        defaultVersion: 0.2.1
    pytorch:
      v1:
        image: kserve/pytorchserver
        defaultVersion: v0.7.0
        defaultGpuVersion: v0.7.0-gpu
      v2:
        image: pytorch/torchserve-kfs
        defaultVersion: 0.4.1
        defaultGpuVersion: 0.4.1-gpu
    triton:
      image: nvcr.io/nvidia/tritonserver
      defaultVersion: 21.09-py3
    pmml:
      image: kserve/pmmlserver
      defaultVersion: v0.7.0
    lightgbm:
      image: kserve/lgbserver
      defaultVersion: v0.7.0
    paddle:
      image: kserve/paddleserver
      defaultVersion: v0.7.0
    alibi:
      image: kserve/alibi-explainer
      defaultVersion: v0.7.0
    art:
      image: kserve/art-explainer
      defaultVersion: v0.7.0
    aix:
      image: kserve/aix-explainer
      defaultVersion: v0.7.0    
