---
### Specify as necessary ###
name: tf2openapi-tagged
substitutions:
  _COMPONENT: "tf2openapi"
  _DOCKERFILE: "./tools/tf2openapi/Dockerfile"
  _CONTEXT: "."
###########################
github:
  owner: kubeflow
  name: kfserving
  push:
    tag: v*.*.*
###########################
build:
  steps:
  - name: docker
    args:
    - "build"
    - "-t"
    - "gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME"
    - "-f"
    - "${_DOCKERFILE}"
    - "${_CONTEXT}"
  images:
  - gcr.io/$REPO_NAME/${_COMPONENT}:$TAG_NAME
