apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: localmodel
    app.kubernetes.io/name: kserve
  name: kserve-localmodelnode-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-localmodelnode-agent-role
subjects:
- kind: ServiceAccount
  name: kserve-localmodelnode-agent
  namespace: kserve
