apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kserve-localmodelnode-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kserve-localmodel-resources.labels" . | nindent 4 }}
    app.kubernetes.io/component: localmodel
    control-plane: "kserve-localmodelnode-agent"
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: "kserve-localmodelnode-agent"
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "kserve-localmodelnode-agent"
        control-plane: "kserve-localmodelnode-agent"
        controller-tools.k8s.io: "1.0"
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      affinity: {{- toYaml (.Values.localmodel.nodeAgent.affinity | default dict) | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.localmodel.nodeAgent.containers.manager.image }}:{{ .Values.localmodel.nodeAgent.containers.manager.tag | default .Values.kserve.version }}"
        imagePullPolicy: {{ .Values.localmodel.nodeAgent.containers.manager.imagePullPolicy }}
        resources: {{- toYaml .Values.localmodel.nodeAgent.containers.manager.resources | nindent 10 }}
        command:
          - /manager

        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true

        volumeMounts:
          - mountPath: /mnt/models
            name: models
            readOnly: false

      {{- with .Values.localmodel.nodeAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      serviceAccountName: kserve-localmodelnode-agent
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml (.Values.localmodel.nodeAgent.tolerations | default list) | nindent 8 }}
      volumes:
        - hostPath:
            path: /models
            type: DirectoryOrCreate
          name: models
