apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: localmodel
    app.kubernetes.io/instance: kserve-localmodel-controller-manager
    app.kubernetes.io/managed-by: kserve-localmodel-controller-manager
    app.kubernetes.io/name: kserve
  name: kserve-localmodel-controller-manager
  namespace: {{ .Release.Namespace }}
