apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: localmodel
    app.kubernetes.io/instance: kserve-localmodelnode-agent
    app.kubernetes.io/managed-by: kserve-localmodelnode-agent
    app.kubernetes.io/name: kserve
  name: kserve-localmodelnode-agent
  namespace: {{ .Release.Namespace }}
