apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/localmodel-serving-cert'
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: localmodel
    app.kubernetes.io/name: kserve
  name: localmodelcache.serving.kserve.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: localmodel-webhook-server-service
      namespace: {{ .Release.Namespace }}
      path: /validate-serving-kserve-io-v1alpha1-localmodelcache
  failurePolicy: Fail
  name: localmodelcache.kserve-webhook-server.validator
  rules:
  - apiGroups:
    - serving.kserve.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - localmodelcaches
  sideEffects: None
