apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llmisvc-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: llmisvc-webhook-server-service.kserve.svc
  dnsNames:
  - llmisvc-webhook-server-service.kserve.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: llmisvc-webhook-server-cert
