apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llmisvc-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llmisvc-leader-election-role
subjects:
- kind: ServiceAccount
  name: llmisvc-controller-manager
  namespace: kserve
