apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: llmisvc-controller-manager
    app.kubernetes.io/name: llmisvc-controller-manager
  name: llmisvc-controller-manager
  namespace: {{ .Release.Namespace }}
