name: Auto Add Issues to Tracking boards
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to projects
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.DEVOPS_APP_ID }}
          private_key: ${{ secrets.DEVOPS_APP_PRIVATE_KEY }}
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/opendatahub-io/projects/40
          github-token: ${{ steps.app-token.outputs.token }}
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/opendatahub-io/projects/45
          github-token: ${{ steps.app-token.outputs.token }}
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/opendatahub-io/projects/42
          github-token: ${{ steps.app-token.outputs.token }}