on:
  pull_request:
    branches:
      - main
      - master
    types: ["closed"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cherry_pick_release_0_10:
    runs-on: ubuntu-latest
    name: Cherry pick into release-0.10
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release-0.10') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cherry pick into release-0.10
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: release-0.10
          labels: |
            cherry-pick
          reviewers: |
            yuzisun
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
