name: "Go Security Scan"

on:
  pull_request:
  schedule:
    # The scheduled workflow runs every Sunday at 00:00 UTC time.
    - cron: '0 0 * * 0'
  workflow_dispatch: { }

jobs:
  go-security-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt=sarif -out=go-security-scan-results.sarif -exclude-dir=pkg/client -exclude-dir=pkg/clientv1alpha1 ./...'

      - name: Upload SARIF file to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: go-security-scan-results.sarif
          category: gosec-tool
